create table TURMAS(
    TURMA_ID int not null AUTO_INCREMENT,
    NOME varchar(255) not null,
    EMPRESA_ID int not null,
    MODALIDADE_ID int not null,
    ATIVO boolean default true,
    DATA_INICIO date not null,
    DATA_FIM date not null,
    CURSO_ID int not null,
    SITUACAO_TURMA_ID int not null,
    PROFESSOR_ID int not null,
    TURNO_ID int not null,
    SALA_ID int not null,
    MAX_ALUNOS int not null,
    MIN_ALUNOS int not null,
    META_ALUNOS int not null,
    USUARIO_ALTERACAO_ID int not null,
    DATA_HORA_ALTERACAO datetime not null default now(),
    USUARIO_CRIACAO_ID int not null,
    DATA_HORA_CRIACAO datetime not null default now(),

    constraint PK_TURMAS primary key(TURMA_ID),
    constraint FK_TURMAS_EMPRESAS foreign key (EMPRESA_ID) references EMPRESAS(EMPRESA_ID),
    constraint FK_TURMAS_FUNCIONARIOS foreign key (PROFESSOR_ID) references FUNCIONARIOS(FUNCIONARIO_ID),
    constraint FK_TURMAS_CURSOS foreign key (CURSO_ID) references CURSOS(CURSO_ID),
    constraint FK_TURMAS_TURNOS foreign key (TURNO_ID) references TURNOS(TURNO_ID),
    constraint FK_TURMAS_SALAS foreign key (SALA_ID) references SALAS(SALA_ID),
    constraint FK_TURMAS_SITUACAO_TURMAS foreign key (SITUACAO_TURMA_ID) references SITUACAO_TURMAS(SITUACAO_TURMA_ID),
    constraint FK_TURMAS_MODALIDADES foreign key (MODALIDADE_ID) references MODALIDADES(MODALIDADE_ID),
    constraint FK_TURMAS_USUARIOS_ALT foreign key (USUARIO_ALTERACAO_ID) references USUARIOS(USUARIO_ID),
    constraint FK_TURMAS_USUARIOS_CRI foreign key (USUARIO_CRIACAO_ID) references USUARIOS(USUARIO_ID)
);