DELIMITER $$
CREATE TRIGGER IMPE_ALTER_DATA_CRIA_EMP_U_BR
BEFORE UPDATE ON EMPRESAS
FOR EACH ROW
BEGIN
    IF NEW.DATA_HORA_CRIACAO <> OLD.DATA_HORA_CRIACAO THEN
        SET @msg = CONCAT('|Não é possível alterar a data de criação. Data de criação atual: ', NEW.DATA_HORA_CRIACAO);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @msg;
    END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER IMPE_ALTER_DATA_CRIA_USU_U_BR
BEFORE UPDATE ON USUARIOS
FOR EACH ROW
BEGIN
    IF NEW.DATA_HORA_CRIACAO <> OLD.DATA_HORA_CRIACAO THEN
        SET @msg = CONCAT('|Não é possível alterar a data de criação. Data de criação atual: ', NEW.DATA_HORA_CRIACAO);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @msg;
    END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER IMPE_ALTER_DATA_CRIA_BAN_U_BR
BEFORE UPDATE ON BANCOS
FOR EACH ROW
BEGIN
    IF NEW.DATA_HORA_CRIACAO <> OLD.DATA_HORA_CRIACAO THEN
        SET @msg = CONCAT('|Não é possível alterar a data de criação. Data de criação atual: ', NEW.DATA_HORA_CRIACAO);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @msg;
    END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER IMPE_ALTER_DATA_CRIA_CAR_U_BR
BEFORE UPDATE ON CARGOS
FOR EACH ROW
BEGIN
    IF NEW.DATA_HORA_CRIACAO <> OLD.DATA_HORA_CRIACAO THEN
        SET @msg = CONCAT('|Não é possível alterar a data de criação. Data de criação atual: ', NEW.DATA_HORA_CRIACAO);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @msg;
    END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER IMPE_ALTER_DATA_CRIA_CBN_U_BR
BEFORE UPDATE ON CONTAS_BANCOS
FOR EACH ROW
BEGIN
    IF NEW.DATA_HORA_CRIACAO <> OLD.DATA_HORA_CRIACAO THEN
        SET @msg = CONCAT('|Não é possível alterar a data de criação. Data de criação atual: ', NEW.DATA_HORA_CRIACAO);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @msg;
    END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER IMPE_ALTER_DATA_CRIA_GRP_U_BR
BEFORE UPDATE ON GRUPOS_CONTAS
FOR EACH ROW
BEGIN
    IF NEW.DATA_HORA_CRIACAO <> OLD.DATA_HORA_CRIACAO THEN
        SET @msg = CONCAT('|Não é possível alterar a data de criação. Data de criação atual: ', NEW.DATA_HORA_CRIACAO);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @msg;
    END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER IMPE_ALTER_DATA_CRIA_MOV_U_BR
BEFORE UPDATE ON MOVIMENTOS
FOR EACH ROW
BEGIN
    IF NEW.DATA_HORA_CRIACAO <> OLD.DATA_HORA_CRIACAO THEN
        SET @msg = CONCAT('|Não é possível alterar a data de criação. Data de criação atual: ', NEW.DATA_HORA_CRIACAO);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @msg;
    END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER IMPE_ALTER_DATA_CRIA_SUB_U_BR
BEFORE UPDATE ON SUBCONTAS
FOR EACH ROW
BEGIN
    IF NEW.DATA_HORA_CRIACAO <> OLD.DATA_HORA_CRIACAO THEN
        SET @msg = CONCAT('|Não é possível alterar a data de criação. Data de criação atual: ', NEW.DATA_HORA_CRIACAO);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @msg;
    END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER IMPE_ALTER_DATA_CRIA_TIP_U_BR
BEFORE UPDATE ON TIPO_DOCUMENTOS
FOR EACH ROW
BEGIN
    IF NEW.DATA_HORA_CRIACAO <> OLD.DATA_HORA_CRIACAO THEN
        SET @msg = CONCAT('|Não é possível alterar a data de criação. Data de criação atual: ', NEW.DATA_HORA_CRIACAO);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @msg;
    END IF;
END $$
DELIMITER ;





